name: Documents

on:
  push:
    branches: [main]
  pull_request:

env:
  PYTHON_VERSION: 3.13

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Restore & Cache Poetry and Dependences
        uses: actions/cache@v4
        id: poetry-cache
        with:
          path: |
            ~/.poetry
            ~/.cache/pypoetry
          key: ${{ env.PYTHON_VERSION }}-${{ hashFiles('docs/poetry.lock') }}

      - name: poetry install
        run: poetry install --no-root
        working-directory: book

      - name: Build Document
        run: |
          poetry run mkdocs build
        working-directory: book

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
